server:
  port: 8016

spring:
#  profiles:
#    active: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
    schemas: boots
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/partyorg"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      mode: always
      continue-on-error: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /




